feat: Add ability to add objects. (#101)
This PR introduces the ability to add objects to copick projects. 

### Model API
Using the model API, you can add a copick object and store the resulting
config using `project.new_object` and `project.save_config`.

```python
    def new_object(
        self,
        name: str,
        is_particle: bool,
        label: Optional[int] = None,
        color: Optional[Tuple[int, int, int, int]] = None,
        emdb_id: Optional[str] = None,
        pdb_id: Optional[str] = None,
        identifier: Optional[str] = None,
        map_threshold: Optional[float] = None,
        radius: Optional[float] = None,
        exist_ok: bool = False,
    ) -> "CopickObject":
        """Create a new pickable object and add it to the configuration.

        Args:
            name: Name of the object.
            is_particle: Whether this object should be represented by points (True) or segmentation masks (False).
            label: Numeric label/id for the object. If None, will use the next available label.
            color: RGBA color for the object. If None, will use a default color.
            emdb_id: EMDB ID for the object.
            pdb_id: PDB ID for the object.
            identifier: Identifier for the object (e.g. Gene Ontology ID or UniProtKB accession).
            map_threshold: Threshold to apply to the map when rendering the isosurface.
            radius: Radius of the particle, when displaying as a sphere.
            exist_ok: Whether existing objects with the same name should be overwritten..

        Returns:
            CopickObject: The newly created object.

        Raises:
            ValueError: If an object with the given name already exists and exist_ok is False.
        """
```

```python
    def save_config(self, config_path: str) -> None:
        """Save the configuration to a JSON file.

        Args:
            config_path: Path to the configuration file to save.
        """
```

### Functional API 
There is an equivalent functional API: 

```python 
def add_object(
    root: CopickRoot,
    name: str,
    is_particle: bool,
    label: Optional[int] = None,
    color: Optional[Tuple[int, int, int, int]] = None,
    emdb_id: Optional[str] = None,
    pdb_id: Optional[str] = None,
    identifier: Optional[str] = None,
    map_threshold: Optional[float] = None,
    radius: Optional[float] = None,
    volume: Optional[np.ndarray] = None,
    voxel_size: Optional[float] = None,
    exist_ok: bool = False,
    save_config: bool = False,
    config_path: Optional[str] = None,
    log: bool = False,
) -> CopickObject:
    """Add a new pickable object to the copick root configuration.

    Args:
        root: The copick root object.
        name: Name of the object.
        is_particle: Whether this object should be represented by points (True) or segmentation masks (False).
        label: Numeric label/id for the object. If None, will use the next available label.
        color: RGBA color for the object. If None, will use a default color.
        emdb_id: EMDB ID for the object.
        pdb_id: PDB ID for the object.
        identifier: Identifier for the object (e.g. Gene Ontology ID or UniProtKB accession).
        map_threshold: Threshold to apply to the map when rendering the isosurface.
        radius: Radius of the particle, when displaying as a sphere.
        volume: Optional volume data to associate with the object.
        voxel_size: Voxel size for the volume data. Required if volume is provided.
        exist_ok: Whether existing objects with the same name should be overwritten..
        save_config: Whether to save the configuration to disk after adding the object.
        config_path: Path to save the configuration. Required if save_config is True.
        log: Whether to log the operation.

    Returns:
        CopickObject: The newly created object.

    Raises:
        ValueError: If volume is provided but voxel_size is not, or if save_config is True but config_path is not provided.
    """
```

And another one to add/update the map volume of an object: 

```python
def add_object_volume(
    root: CopickRoot,
    object_name: str,
    volume: np.ndarray,
    voxel_size: float,
    log: bool = False,
) -> CopickObject:
    """Add volume data to an existing pickable object.

    Args:
        root: The copick root object.
        object_name: Name of the existing object.
        volume: Volume data to add.
        voxel_size: Voxel size of the volume data.
        log: Whether to log the operation.

    Returns:
        CopickObject: The updated object.

    Raises:
        ValueError: If the object does not exist or if the object is not a particle.
    """
```

### CLI

There are also equivalent CLI commands: 

```bash
copick add object-definition --help
```

```
copick 1.6.1
------------
Usage: copick add object [OPTIONS]

  Add a pickable object to the project configuration.

Options:
  -c, --config PATH               Path to the configuration file.  [env var:
                                  COPICK_CONFIG]
  --name TEXT                     Name of the object to add.  [required]
  --object-type [particle|segmentation]
                                  Type of object: 'particle' for point
                                  annotations or 'segmentation' for mask
                                  annotations.  [default: particle]
  --label INTEGER                 Numeric label/id for the object. If not
                                  provided, will use the next available label.
  --color R,G,B,A                 RGBA color for the object as comma-separated
                                  values (e.g. '255,0,0,255' for red).
  --emdb-id TEXT                  EMDB ID for the object.
  --pdb-id TEXT                   PDB ID for the object.
  --identifier TEXT               Identifier for the object (e.g. Gene
                                  Ontology ID or UniProtKB accession).
  --map-threshold FLOAT           Threshold to apply to the map when rendering
                                  the isosurface.
  --radius FLOAT                  Radius of the particle, when displaying as a
                                  sphere.
  --volume PATH                   Path to volume file to associate with the
                                  object.
  --volume-format [mrc|zarr]      Format of the volume file ('mrc' or 'zarr').
                                  Will guess from extension if not provided.
  --voxel-size FLOAT              Voxel size for the volume data. Required if
                                  volume is provided.
  --exist-ok / --no-exist-ok      Whether existing objects with the same name
                                  should be overwritten.  [default: no-exist-
                                  ok]
  --debug / --no-debug            Enable debug logging.  [default: no-debug]
  --help                          Show this message and exit.
```

and 

```bash
 copick add object-volume --help  
```

```
copick 1.6.1
------------
Usage: copick add object-volume [OPTIONS]

  Add volume data to an existing pickable object.

Options:
  -c, --config PATH           Path to the configuration file.  [env var:
                              COPICK_CONFIG]
  --object-name TEXT          Name of the existing object.  [required]
  --volume-path PATH          Path to the volume file.  [required]
  --volume-format [mrc|zarr]  Format of the volume file ('mrc' or 'zarr').
                              Will guess from extension if not provided.
  --voxel-size FLOAT          Voxel size of the volume data in Angstrom.
                              [required]
  --debug / --no-debug        Enable debug logging.  [default: no-debug]
  --help                      Show this message and exit.
```